In [1]:
import pandas as pd

In [2]:
raw = pd.read_excel('Resultados 2da visita.xlsx')

In [8]:
raw.head()

,Trial,Participante 1,Participante 2,Participante 3,Participante 4,Participante 5,Participante 6,Participante 7,Participante 8,Participante 9,...,Participante 3.1,Participante 4.1,Participante 5.1,Participante 6.1,Participante 7.1,Participante 8.1,Participante 9.1,Participante 10.1,Participante 11.1,Participante 12.1
0,1,21.0,13.0,30.0,40.0,28,11.0,20,92.0,89.0,...,0.166667,0.222222,0.155556,0.061111,0.111111,0.511111,0.494444,0.038889,0.211111,0.127778
1,2,24.0,0.0,89.0,60.0,0,2.0,43,12.0,10.0,...,0.494444,0.333333,0.000000,0.011111,0.238889,0.066667,0.055556,0.016667,0.016667,0.022222
2,3,1.0,0.0,12.0,59.0,13,0.0,5,19.0,68.0,...,0.066667,0.327778,0.072222,0.000000,0.027778,0.105556,0.377778,0.000000,0.044444,0.016667
3,4,0.0,3.0,1.0,79.0,2,0.0,6,16.0,86.0,...,0.005556,0.438889,0.011111,0.000000,0.033333,0.088889,0.477778,0.038889,0.005556,0.050000
4,5,0.0,0.0,4.0,88.0,56,0.0,4,3.0,20.0,...,0.022222,0.488889,0.311111,0.000000,0.022222,0.016667,0.111111,0.011111,0.027778,0.011111

In [31]:
for column in raw.columns:
    if raw[column].isnull().all():
        rawdr = raw.drop(column, axis = 1)

In [43]:
normdf = rawdr.ix[:,13:]

In [44]:
normdf

,Trial.1,Participante 1.1,Participante 2.1,Participante 3.1,Participante 4.1,Participante 5.1,Participante 6.1,Participante 7.1,Participante 8.1,Participante 9.1,Participante 10.1,Participante 11.1,Participante 12.1
0,1,0.116667,0.072222,0.166667,0.222222,0.155556,0.061111,0.111111,0.511111,0.494444,0.038889,0.211111,0.127778
1,2,0.133333,0.000000,0.494444,0.333333,0.000000,0.011111,0.238889,0.066667,0.055556,0.016667,0.016667,0.022222
2,3,0.005556,0.000000,0.066667,0.327778,0.072222,0.000000,0.027778,0.105556,0.377778,0.000000,0.044444,0.016667
3,4,0.000000,0.016667,0.005556,0.438889,0.011111,0.000000,0.033333,0.088889,0.477778,0.038889,0.005556,0.050000
4,5,0.000000,0.000000,0.022222,0.488889,0.311111,0.000000,0.022222,0.016667,0.111111,0.011111,0.027778,0.011111
5,6,0.005556,0.038889,0.027778,0.372222,0.088889,NaN,0.005556,0.016667,0.116667,0.000000,0.038889,0.011111
6,7,0.000000,0.000000,0.005556,0.355556,0.005556,NaN,0.272222,0.011111,0.011111,0.005556,0.011111,0.011111
7,8,NaN,0.005556,0.005556,NaN,0.011111,NaN,0.027778,0.016667,0.211111,0.027778,0.011111,NaN
8,9,NaN,NaN,0.000000,NaN,0.005556,NaN,0.038889,0.033333,NaN,0.005556,0.000000,NaN
9,10,NaN,NaN,NaN,NaN,0.005556,NaN,0.022222,NaN,NaN,NaN,NaN,NaN